### 1. Нормальное создание - ждём 201
@host = http://localhost:5295

POST {{host}}/api/posts
Content-Type: application/json

{
  "title": "Test post",
  "content": "Testing publish"
}
### Опубликовать - ждём 200 и isPublished: true
POST {{host}}/api/posts/4/publish

### Снять - ждём 200 и isPublished: false
POST {{host}}/api/posts/4/unpublish

### Несуществующий - ждём 404
POST {{host}}/api/posts/999/publish